version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      timezone: "weekly"

  - directory: /frontend/
    open-pull-requests-limit: 5
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      timezone: "weekly"

  - directory: /backend
    open-pull-requests-limit: 5
    package-ecosystem: pip
    rebase-strategy: auto
    schedule:
      timezone: "weekly"

  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: docker
    rebase-strategy: auto
    schedule:
      timezone: "weekly"
