repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: ["json"]
      - id: trailing-whitespace
        exclude_types: ["json"]
      - id: check-json
      - id: pretty-format-json
        exclude: "(package.*|Pipfile.*|.*/tests/.*)"
        args: ["--autofix"]
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-symlinks
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--django"]
        name: "Tests should start with test_*.py"

  - repo: https://github.com/crate-ci/typos
    rev: v1.31.0
    hooks:
      - id: typos
        exclude_types: ["json"]
        exclude: migrations
        args: [] # Uncomment if you want to autofix

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        exclude: migrations
        args:
          [
            "--profile",
            "black",
            "--project",
            "bookmarks",
            "--project",
            "places",
            "--project",
            "watched",
            "--project",
            "wiki",
          ]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.24.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.11.2"
    hooks:
      - id: ruff
        exclude: migrations
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        exclude: migrations
