repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: ["json"]
      - id: trailing-whitespace
        exclude_types: ["json"]
      - id: check-json
      - id: pretty-format-json
        exclude: "(package.*|.*/tests/.*)"
        args: ["--autofix"]
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-symlinks
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--django"]
        name: "Tests should start with test_*.py"

  - repo: https://github.com/crate-ci/typos
    rev: v1.50.3
    hooks:
      - id: typos
        exclude_types: ["json"]
        exclude: migrations
        args: [] # Uncomment if you want to autofix

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.33.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "6.1"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.16.10"
    hooks:
      - id: ruff-check
        exclude: migrations
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        exclude: migrations

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.22
    hooks:
      - id: uv-lock
