version: "3.5"
services:
  backend:
    build:
      context: ./
      target: backend
    volumes:
      - "./frontend/src/api:/usr/src/app/homepage/frontend/src/api"
      - "./backend/database.spatialite:/usr/src/app/homepage/backend/database.spatialite"
    command: bash -c "python manage.py out_bookmarks && python manage.py out_wiki && python manage.py out_places && python manage.py out_watched"

  frontend:
    build:
      context: ./
      target: frontend
    volumes:
      - "./frontend/src/api:/usr/src/app/homepage/frontend/src/api"
      - "./frontend/build:/usr/src/app/homepage/frontend/build"
    command: npm run-script build

  admin:
    build:
      context: ./
      target: backend
    volumes:
      - "./backend/database.spatialite:/usr/src/app/homepage/backend/database.spatialite"
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
