web:
  image: nginx
  volumes:
    - "./static/:/usr/share/nginx/html/"
  ports:
    - "80:80"

api:
  build: .
  links:
    - db:db
  ports:
    - "8000:8000"

db:
  image: mariadb:5
  environment:
    - MYSQL_DATABASE=franhpnet
    - MYSQL_USER=mysql_user
    - MYSQL_PASSWORD=mysql_password
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
  ports:
    - "3306:3306"
