FROM python:3.10

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install \
        firefox-esr \
        binutils \
        libproj-dev \
        gdal-bin \
        libsqlite3-mod-spatialite

ADD backend/requirements.txt /
RUN pip install -r /requirements.txt

RUN mkdir -p /usr/src/app/homepage
ADD . /usr/src/app/homepage

WORKDIR /usr/src/app/homepage/backend