# Generated by Django 2.0.2 on 2018-03-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0005_auto_20180304_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='my_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
