# Generated by Django 3.0.5 on 2020-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200415_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='attendants',
            field=models.CharField(choices=[('together', 'Fran&Sara'), ('fran', 'Fran'), ('sara', 'Sara'), ('home', 'Home')], max_length=255),
        ),
    ]
