# Generated by Django 3.0.5 on 2020-04-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
