# Generated by Django 4.1.11 on 2023-09-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0002_alter_bookmark_id_alter_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
