# Generated by Django 3.0.5 on 2020-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
