# Generated by Django 3.0.5 on 2020-04-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_bookmark_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
