# Generated by Django 2.0.2 on 2018-03-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-year']},
        ),
    ]
