# Generated by Django 2.0.2 on 2018-03-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0003_auto_20150408_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvseries',
            options={'ordering': ['-rating', 'name'], 'verbose_name_plural': 'TVSeries'},
        ),
    ]
