# Generated by Django 2.0.2 on 2018-03-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0004_auto_20180303_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_type', models.CharField(choices=[('movie', 'Movie'), ('tvSeries', 'TV Series')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('year', models.DateField()),
                ('imdbid', models.CharField(max_length=20)),
                ('my_rating', models.FloatField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-my_rating', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='TVSeries',
        ),
    ]
