# Generated by Django 2.0.2 on 2018-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0006_auto_20180304_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title_type',
            field=models.CharField(max_length=20),
        ),
    ]
