# Generated by Django 2.0.2 on 2018-03-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0008_auto_20180304_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
