name: CI

on:
  push:
    branches: [master, feature/rewrite-2020]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd containers/homepage
            docker-compose pull
            docker-compose run backend
            docker-compose run frontend
