# Generated by Django 3.0.5 on 2020-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title_type', models.CharField(blank=True, choices=[('movie', 'Movie'), ('tvSeries', 'TV Series'), ('short', 'Short'), ('tvMovie', 'TV Movie'), ('tvMiniSeries', 'TV Miniseries'), ('video', 'Video'), ('book', 'Book')], max_length=50, null=True)),
                ('my_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
