# Generated by Django 3.0.5 on 2020-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watched', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='ranking_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
