# Generated by Django 6.1.1 on 2026-10-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watched', '0002_alter_title_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='title',
            name='tracking_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Planning'), (1, 'In progress'), (2, 'Paused'), (3, 'Completed'), (4, 'Dropped')], null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='my_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
