# Generated by Django 3.0.5 on 2020-04-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watched', '0002_title_ranking_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='imdb_rating',
            new_name='site_rating',
        ),
        migrations.AlterField(
            model_name='title',
            name='reference',
            field=models.CharField(max_length=255),
        ),
    ]
