# Generated by Django 6.1.1 on 2026-10-03 16:05

from django.db import migrations, models


def normalize_title_types(apps, schema_editor):
    Title = apps.get_model("watched", "Title")
    Title.objects.filter(title_type="tvMiniSeries").update(title_type="tvSeries")
    Title.objects.filter(title_type__in=["tvMovie", "video"]).update(
        title_type="movie"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("watched", "0003_title_tracking_id_title_tracking_status_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_title_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="title",
            name="title_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("movie", "Movie"),
                    ("tvSeries", "TV Series"),
                    ("short", "Short"),
                    ("book", "Book"),
                    ("game", "Game"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
