# Generated by Django 3.0.5 on 2020-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watched', '0003_auto_20200408_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title_type',
            field=models.CharField(blank=True, choices=[('movie', 'Movie'), ('tvSeries', 'TV Series'), ('short', 'Short'), ('tvMovie', 'TV Movie'), ('tvMiniSeries', 'TV Miniseries'), ('video', 'Video'), ('book', 'Book'), ('game', 'Game')], max_length=50, null=True),
        ),
    ]
